version: '4'

services:

  app:
    image: osama8558/osama-auto-app
    container_name: osama-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: osama-nginx
    ports:
      - "8088:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
